### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by akhar** [toburger/elm-xml-parser#2]
Can you provide any example of usage, please? I just can't realise how to use it.

**Comment by toburger** [comment]
There are two examples in the repo:
- Output of the result with toString: https://github.com/toburger/elm-xml-parser/blob/master/Test/Xml/Parser.elm
- Decodes directly to a Json.Value: https://github.com/toburger/elm-xml-parser/blob/master/Test/Xml/Decode.elm

But you are right, I should provide better samples.

**Comment by akhar** [comment]
Thanks!
