### ISSUE TITLE
Having a comment following the XML declaration tag

### ISSUE THREAD

**Issue by ssemakin** [toburger/elm-xml-parser#3]
Hey Tobias, thanks for the lib and the effort - this is something I've been looking for. I'm running into an issue when having a comment after the declaration tag. I'm new to Elm so I wasn't sure how to resolve this. Not sure how valid XML it is though. 

Here goes example:

``` elm
sample33: String
sample33 =
  """
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- some comment -->
<error id="no">
</error>
  """
```

**Comment by toburger** [comment]
Hi @ssemakin, it should be possible to have a comment before or after the root element.

I will fix it. It is a breaking change, because the result of the parseXml is now a `List XmlAst`, not a single `XmlAst`.

**Comment by ssemakin** [comment]
Hi Tobias, thanks for fixing it so fast!

I just tried it and it works fine, just keep in mind that in case there're several comments coming one after another, then only one comment is parsed to a json field and the rest are lost, not sure if it is intended so.

**Comment by toburger** [comment]
Yes you are right! Should be handled as a list of comments, but I didn't wanted to over complicate things. Normally comments isn't data required by the consuming code so it is negligible in most of the cases.
